### ISSUE TITLE
Better specification of setup requirements

### ISSUE THREAD

**Issue by maxbartolo** [uclmr/jack#346]
I think it requires cuDNN > v6 because v5 didn’t work for me and also an explanation of why CUDA 8.0 is specified (ie will 7.5 work fine or is that there so you don’t update to 9.0? - I’m not sure because I just updated to 8.0). Also, what Python version? I updated to 3.6 since it uses tensorflow 1.4 but getting a runtime warning which seems to indicate that I should have left it at 3.5. Also, you have to manually install tensorflow-gpu to get it running on the GPUs (I think) and it doesn’t get installed with the requirements.

**Comment by dirkweissenborn** [comment]
That is correct. The setup is quite messy at the moment. I think we should work this over. We should probably also switch from egg to whl when building dists. What do you think @pminervini ? Can you handle this?

**Comment by pminervini** [comment]
Yup

**Comment by pminervini** [comment]
I can set up a nightly cron job for building a `jack` wheel:

http://jack.neuralnoise.com/dist/

Then it would be possible to install `jack` as follows:

```bash
pip3 install http://jack.neuralnoise.com/dist/jack-0.1.0-py2.py3-none-any.whl
```

But maybe there's a better way of handling this whole thing.

**Comment by dirkweissenborn** [comment]
I think  `jack` will primarily be used as a whitebox framework. I, for instance, never use the `setup.py` script because I don't want jack to get installed on my machine. What I would like is a good documentation for how to setup jack properly without having to install it. I mean, we already have a `requirements.txt` which should be enough in addition with a good documentation on how to setup `jack` with CPU or GPU, respectively.

**Comment by pminervini** [comment]
@dirkweissenborn ok - I'm now working on using `pip install -e .[tf]` and `pip install -e .[tf_gpu]` for installing `jack` without/with GPU suport; I just need to fix a couple of bugs and merge

**Comment by pminervini** [comment]
Bam: https://github.com/uclmr/jack/pull/349
