### ISSUE TITLE
Quick Start Instructions result in Unexpected Argument Error

### ISSUE THREAD

**Issue by adityachemudupaty** [uclmr/jack#395]
I was just trying to run through the Quick Start Notebook, and this is the error I am getting whenever I run the steps for the FastQA model. I feel like I'm missing something really obvious but I'm not sure. Any suggestions?
![jtr-quickstart-max_value-error](https://user-images.githubusercontent.com/8845245/53834965-ecd82580-3f51-11e9-9ce3-d8fe764b0373.png)

**Comment by v1n2e7t** [comment]
Have you solved or found a way around this yet?

**Comment by adityachemudupaty** [comment]
No I haven't. I tried a bunch of things that didn't work, but I don't even remember what I tried now...

**Comment by s-lilo** [comment]
Maybe it's a bit late, but I ran into the same error and found how to fix it. Jack uses the progressbar package to show how it's progressing while training. When creating the progress bar, the object should needs the argument 'maxval', but it's receiving 'max_value', thus the error. You need to change it in two different places: one where the error is pointing at and another somewhere else in the code (I can't remember exactly where, sorry). Otherwise, you will get the same error when the program finishes training (and trust me, that's not funny at all D:).

**Comment by adityachemudupaty** [comment]
Okay. i'll try it and get back to you. Thanks for the solution.

**Comment by adityachemudupaty** [comment]
I changed the 'max_value' to 'maxval' in jack/core/reader.py and ran the notebook again, and the issue was fixed. I did not run into the error after finishing the training.
